### ISSUE TITLE
Pmod Libraries do not work with Arty-S7-50

### ISSUE THREAD

**Issue by cfsterpka** [Digilent/vivado-library#15]
I've been attempting to use Pmods with my Arty-S70-50 board in Vivado and the only option I am given is the PmodBLE.  I've noticed that when I select the generic Arty board that I am able to load the entire set of Pmods.  I'm guessing this is related to [this issue](https://forums.xilinx.com/t5/7-Series-FPGAs/How-to-use-Pmod-SD-with-Arty-S7-50-board/td-p/821017) in the Xilinx forum.  Is there no support for Pmods other than the PmodBLE with the Arty-S7-50 or is this a Vivido issue?

**Comment by elodg** [comment]
Each IP has a list of supported parts on which it was verified as working. This is found in the component.xml file. For example [https://raw.githubusercontent.com/Digilent/vivado-library/master/ip/Pmods/PmodACL2_v1_0/component.xml](url):
`      <xilinx:supportedFamilies>
        <xilinx:family xilinx:lifeCycle="Production">zynq</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">virtex7</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">qvirtex7</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">kintex7</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">kintex7l</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">qkintex7</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">qkintex7l</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">artix7</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">artix7l</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">aartix7</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">qartix7</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">qzynq</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">azynq</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">virtexu</xilinx:family>
        <xilinx:family xilinx:lifeCycle="Production">kintexu</xilinx:family>
      </xilinx:supportedFamilies>`

Since Spartan-7 is a relatively new part, it is probably not present in the list. Instantiate the IP in a project with a compatible part, edit in IP packager and add spartan7 to the list. Or edit component.xml manually and add a new line. Either way, test the IP in a spartan7 project and contribute back, if it works.

**Comment by cfsterpka** [comment]
Thank you for you help.  I can confirm that this worked to at least be able to use the Pmods with the Arty-s7-50 in Vivado, I will perform some tests and see if I can get the Pmods that I have to actually function with the board (currently I only have the RTC and SD Pmods).
