### ISSUE TITLE
RTCC example code does not output actual time

### ISSUE THREAD

**Issue by mahdiunh** [Digilent/vivado-library#23]
Hello guys,
I managed to run the RTCC example code on my Arty board, but I am receiving a pre-defined date and time over my terminal, which kind of seems useless, since I need the RTTC pmod to find the actual time for me and print that out. Isn't that what RTCC is used for? or maybe it is just the example code that does not synchronize the time? Is there any other example code I can use to get the actual time?
Thanks
Mahdi

**Comment by atangzwj** [comment]
The PmodRTCC does not have a way of synchronizing with the current time. The RTCC can be initialized to the current time using the provided example program and keep track of time from that point forward so long as power is provided. A coin cell battery can be used to supply power to the RTCC so that the RTCC can continue to track time without power from the host board. 

See the RTCC's reference manual for more details: https://reference.digilentinc.com/reference/pmod/pmodrtcc/reference-manual
