### ISSUE TITLE
PModSD Data Throughput Speeds

### ISSUE THREAD

**Issue by Lamvo428** [Digilent/vivado-library#39]
Hello,

I've been using the PModSD IP and code with a lot of success.  Thank you for developing this.  What I would like to know is, how can I speed up the data transfer?  

I've tested the IP core with a microblaze on an ARTY board and on a ZYBO with a zync.  The data rates top off at about 100kB/sec.  It appears the bottleneck is at the SPI/SDCS interface?  I'm not sure.  

If someone can point me to where I can get started update dating the IP or the software to speed up the data throughput of PModSD, I will be a very happy camper.  

Thanks!

**Comment by elodg** [comment]
This is more of a forum question rather than bug report, but I will answer it here.
The IP uses SPI and not SD native interface. Therefore, the data rate is limited to a quarter just by the interface. Other interface timing specs are the same for SPI and SD, so the clock can reach 25MHz (Default Speed) or 50MHz (High Speed). So the theoretical data speed you can reach over SPI is at least 25Mbps or 3.125MB/s. At least read commands should get close to this speed.
Check your clock signals for the Quad SPI IP and the divider settings. For initalization you will need 100kHz but after that you can drop the divider setting to reach the maximum clock supported by your card.

As far as I know write speeds guaranteed by Class specs are only valid for SD native interface, so do not expect writes to perform at these speeds.

**Comment by Lamvo428** [comment]
Hello Elod,

Thanks for getting back to me.  Yes I realize it is more of a forum
question.  I wasn't sure where to ask it.

I may have another dumb questions, but where do I change the QUAD SPI IP
divider?  I've been looking around in the C code, ie xspi_options.c, xpi.h,
xspi.c, but can seem to find anything.

In vivado, the PmodSD IP core abstracts away a lot of the details, (I'm
sure this was intended) so I didn't find any clock information there.  I
see some setting in the zync IP core.  I'm new to zync, but have worked
with microblaze.

Any pointers will help.  Even if its to a message board elsewhere.

Thanks!
-----
Lam Vo
lamvo428@gmail.com
(201) 988-3151
Timing is everything.
